# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'
use_frameworks!

def shared_pods
pod 'RxSwift', '~> 5'
pod 'RxCocoa', '~> 5'
pod 'RxDataSources', '~> 4.0'
pod 'Kingfisher', '~> 5.0'
#DI Container -> https://github.com/Swinject/Swinject
pod 'Swinject'
pod 'SVProgressHUD'
end
	 
target 'RXMVVMC' do
 shared_pods
end

target 'RXMVVMCDev' do
 shared_pods
end
